version: '3.8'

services:
  automatic1111.v1.6:
    container_name: automatic1111-nvidia-docker
    image: krim/automatic1111-nvidia-docker
    restart: unless-stopped
    build:
      context: .
      args:
        AUTOMATIC1111_VERSION: "v1.10.0"
        #HTTP_PROXY: "http://10.60.3.254:3128"
        #HTTPS_PROXY: "http://10.60.3.254:3128"
    ports:
      - "7860:7860"
    environment:
      - USE_CUDA_118=true
      - USE_XFORMERS=true
      - IS_LOWVRAM=false
      - IS_MEDVRAM=false
    volumes:
      - automatic1111_data:/home/appuser/stable-diffusion-webui
    mem_limit: "128G"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

volumes:
  automatic1111_data:
    external: true

#docker volume create --driver local --opt type=none --opt device=/srv/automatic --opt o=bind automatic1111_data